"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 5000
palette = 'me'

format = """
╭──── \
[](fg:path)\
$directory\
[](fg:path bg:vcs)\
$git_branch\
$git_status\
$c\
$golang\
$nodejs\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$rust\
[](fg:vcs bg:time)\
$time\
[ ](fg:time)\
$cmd_duration\
$line_break\
╰─ \
$character """

[c]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[character]
disabled = false
success_symbol = '[ ](fg:success)'
error_symbol = '[ ](fg:error)'
vimcmd_symbol = '[ ](fg:edit)'
vimcmd_replace_one_symbol = '[ ](bold fg:edit_select)'
vimcmd_replace_symbol = '[ ](bold fg:edit_select)'
vimcmd_visual_symbol = '[ ](bold fg:edit_select)'

[cmd_duration]
disabled = false
min_time_to_notify = 5000
show_milliseconds = false
show_notifications = false
format = "[[$duration](fg:time italic red)]($style)"

[directory]
disabled = false
style = "bg:path fg:text"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"code" = "󰲋 "

[git_branch]
disabled = false
symbol = ""
format = '[[ $symbol $branch](fg:text bg:vcs)]($style)'

[git_status]
disabled = false
modified = "${count}"
format = '[[ $all_status$ahead_behind](fg:text bg:vcs)]($style)'

[golang]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[java]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[kotlin]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[line_break]
disabled = false

[lua]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[nodejs]
symbol = " "
format = '[[ $symbol](fg:text bg:lang)]($style)'

[os]
disabled = false
style = "bg:who fg:text"

[os.symbols]
Alpine = ""
Arch = "󰣇"
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Raspbian = "󰐿"
Ubuntu = "󰕈"
Windows = ""

[palettes.me]
edit         = "172"
edit_select  = "123"
error        = "124"
lang         = "248"
path         = "250"
success      = "035"
text         = "000"
time         = "244"
who          = "252"
vcs          = "248"

[python]
symbol = " "
format = '[[ $symbol(\(#$virtualenv\))](fg:text bg:lang)]($style)'

[rust]
symbol = "󱘗 "
format = '[[ $symbol(\(#$virtualenv\))](fg:text bg:lang)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time](fg:text bg:time)]($style)'

[username]
show_always = true
style_user = "bg:who fg:text"
style_root = "bg:who fg:text"
format = '[ $user]($style)'
